### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by alu0101206479** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct08-filesystem-notes-app-alu0101206479#1]
Buenas, no entiendo por que me da mal los github actions cuando yo hago las pruebas en mi máquina y me da todo bien.

@esegredo @amarrerod

**Comment by alu0101206479** [comment]
Creo que es porque yo en mis pruebas, lo que hago es ir comprobando si se me va modificando el contenido del directorio usuario_prueba y por eso en la máquina me funciona, pero creo que cuando se hacen las pruebas en el github actions (Online), no se me modifica el directorio de prueba_usuario y por eso me da errores.

Creo que una manera de solucionarlo es en vez de hacer las comprobaciones con el contenido del directorio, hacerlo con el contenido del atributo "notas" del usuario. Lo que antes de proceder a solucionarlo quiero que me confirmen que es por lo que estoy diciendo lo que me da error y no por otra cosa.

Muchas gracias y espero su respuesta.

**Comment by esegredo** [comment]
Hola, buenos días.

Con las versiones 10 y 12 de Node.js no funciona porque la función rmSync del módulo fs no existía en dichas versiones. Es una funcionalidad añadida a partir de Node 14. Si accedes a la información de ejecución de los flujos de trabajo para la versión 10 y 12 de Node, verás algo como esto en el paso del npm run test:

TypeError: fs.rmSync is not a function

Respecto a las versiones 14 y 15, si que te están fallando algunas pruebas. Piensa que puedes hacerlo como lo has pensado en un inicio, pero el repositorio que se descarga y despliega en la MV de ejecucion de GitHub debe tener las condiciones necesarias para que luego todas tus pruebas vayan pasando. Si, por ejemplo, no existe un fichero que las pruebas esperan que exista de entrada, todo fallará.

Espero haberte ayudado con lo anterior.

Saludos.

@alu0101206479

**Comment by alu0101206479** [comment]
Lo que pasa es que las pruebas que me fallan me fallan solo aquí en github porque en la máquina no me fallan ya que da igual si está el fichero o no está porque se crea y se borra con las pruebas correspondientes. Ósea en la máquina no hay ninguna prueba que me falle, pero probaré otras cosas a ver.

@esegredo @amarrerod

**Comment by alu0101206479** [comment]
Que va profe, puede ver que acabo de hacer un commit y en vez de usar el fichero para comprobar uso el atributo notas de usuario y nada no funciona, lo que haré para arreglarlo es no meter ningun expect dentro de los it, sino solo meter lo que es las funciones como el añadir, el remove, etc.

@esegredo @amarrerod

**Comment by alu0101206479** [comment]
O obviaré la prueba del remove y no la haré, porque se que me funciona y es la que me esta dando problemas

**Comment by alu0101206479** [comment]
Efectivamente profe, obvie la prueba del rm, que era la que me estaba dando problemas y use el atributo notas en vez de el contenido del directorio para comprobar, y así va todo bien.

Muchas gracias y disculpe las molestias.

@esegredo @amarrerod
